steps:
  # Docker Build
  - name: node:10.15.1
  - entrypoint: npm
  - args: [ "run", "create-env" ]
  - env:
    - 'VITE_GOOGLE_MAPS_API_KEY=${_MY_SECRET_KEY}'
  - name: 'gcr.io/cloud-builders/docker'
    script: |
      docker build -t europe-north1-docker.pkg.dev/$PROJECT_ID//my-docker-repo/myimage .
      automapSubstitutions: true
images:
  - 'europe-north1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/myimage'
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    versionName: projects/swopp-436713/secrets/projects/844462537245/secrets/VITE_GOOGLE_MAPS_API_KEY/versions/latest
    env: 'VITE_GOOGLE_MAPS_API_KEY'